env_variables:
  PORT: 8000
  DB_URL: mongodb+srv://admin:Phuc20010@cluster0.tyabe.mongodb.net/shop-mp?retryWrites=true&w=majority
  CLOUDINARY_CLOUD_NAME: ecommerce-mp
  CLOUDINARY_API_KEY: 945425879786779
  CLOUDINARY_API_SECRET: T2tSAEbcEjWdTllmTFmDb3PiOkw
  STRIPE_SECRET: sk_test_51HrpPwFdX4LUv0XVSVOUq420GtUMR1hlwefPypWRkQ6WDQFQUpwQYXGGCzCtVnzJXo7GOJuyuezGTgTFpQBaL01q00X01SQcZd
runtime: nodejs10
service: api
